site_name: thienqc
site_description: thienqc's blog
site_url: https://thienqc.github.io/blog/
site_author: thienqc

plugins:
  - search
  - exclude-search:
      exclude: [newsletter/*]
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index
  - mkdocs-newsletter

markdown_extensions:
  - abbr
  - admonition
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
    name: 'material'
    # custom_dir: overrides
    icon:
      logo: fontawesome/solid/brain
      # favicon: assets/meta/brain-solid.png
    font:
        text: Roboto
        code: Roboto Mono
    language: en
    
    palette:
      # Light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: deep purple
        accent: light blue
    features:
      - navigation.footer
      - navigation.instant
      - navigation.top
      - content.code.annotate
      - search.suggest
      - search.highlight

copyright: Copyright &copy; 2023 thienqc



extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/yds.thienqc/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/thienqc/

